#include "FilterFactory.hpp"
#include <algorithm>
#include <cctype>
#include <stdexcept>
std::shared_ptr<FilterBase> CreateFilter(FilterType type) {
    switch(type) {
        case FilterType::Acopy:
            return std::make_shared<Acopy>();
        case FilterType::Aderivative:
            return std::make_shared<Aderivative>();
        case FilterType::Aintegral:
            return std::make_shared<Aintegral>();
        case FilterType::Alatency:
            return std::make_shared<Alatency>();
        case FilterType::Amultiply:
            return std::make_shared<Amultiply>();
        case FilterType::Anull:
            return std::make_shared<Anull>();
        case FilterType::Apsnr:
            return std::make_shared<Apsnr>();
        case FilterType::Areverse:
            return std::make_shared<Areverse>();
        case FilterType::Asdr:
            return std::make_shared<Asdr>();
        case FilterType::Ashowinfo:
            return std::make_shared<Ashowinfo>();
        case FilterType::Asisdr:
            return std::make_shared<Asisdr>();
        case FilterType::Earwax:
            return std::make_shared<Earwax>();
        case FilterType::Volumedetect:
            return std::make_shared<Volumedetect>();
        case FilterType::Anullsink:
            return std::make_shared<Anullsink>();
        case FilterType::Addroi:
            return std::make_shared<Addroi>();
        case FilterType::Alphaextract:
            return std::make_shared<Alphaextract>();
        case FilterType::Alphamerge:
            return std::make_shared<Alphamerge>();
        case FilterType::Amplify:
            return std::make_shared<Amplify>();
        case FilterType::Atadenoise:
            return std::make_shared<Atadenoise>();
        case FilterType::Avgblur:
            return std::make_shared<Avgblur>();
        case FilterType::Backgroundkey:
            return std::make_shared<Backgroundkey>();
        case FilterType::Bbox:
            return std::make_shared<Bbox>();
        case FilterType::Bench:
            return std::make_shared<Bench>();
        case FilterType::Bilateral:
            return std::make_shared<Bilateral>();
        case FilterType::Bitplanenoise:
            return std::make_shared<Bitplanenoise>();
        case FilterType::Blackdetect:
            return std::make_shared<Blackdetect>();
        case FilterType::Blend:
            return std::make_shared<Blend>();
        case FilterType::Blockdetect:
            return std::make_shared<Blockdetect>();
        case FilterType::Blurdetect:
            return std::make_shared<Blurdetect>();
        case FilterType::Bm3d:
            return std::make_shared<Bm3d>();
        case FilterType::Bwdif:
            return std::make_shared<Bwdif>();
        case FilterType::Cas:
            return std::make_shared<Cas>();
        case FilterType::Ccrepack:
            return std::make_shared<Ccrepack>();
        case FilterType::Chromahold:
            return std::make_shared<Chromahold>();
        case FilterType::Chromakey:
            return std::make_shared<Chromakey>();
        case FilterType::Chromanr:
            return std::make_shared<Chromanr>();
        case FilterType::Chromashift:
            return std::make_shared<Chromashift>();
        case FilterType::Ciescope:
            return std::make_shared<Ciescope>();
        case FilterType::Codecview:
            return std::make_shared<Codecview>();
        case FilterType::Colorbalance:
            return std::make_shared<Colorbalance>();
        case FilterType::Colorchannelmixer:
            return std::make_shared<Colorchannelmixer>();
        case FilterType::Colorcontrast:
            return std::make_shared<Colorcontrast>();
        case FilterType::Colorcorrect:
            return std::make_shared<Colorcorrect>();
        case FilterType::Colorize:
            return std::make_shared<Colorize>();
        case FilterType::Colorkey:
            return std::make_shared<Colorkey>();
        case FilterType::Colorhold:
            return std::make_shared<Colorhold>();
        case FilterType::Colorlevels:
            return std::make_shared<Colorlevels>();
        case FilterType::Colormap:
            return std::make_shared<Colormap>();
        case FilterType::Colorspace:
            return std::make_shared<Colorspace>();
        case FilterType::Colortemperature:
            return std::make_shared<Colortemperature>();
        case FilterType::Convolution:
            return std::make_shared<Convolution>();
        case FilterType::Convolve:
            return std::make_shared<Convolve>();
        case FilterType::Copy:
            return std::make_shared<Copy>();
        case FilterType::Corr:
            return std::make_shared<Corr>();
        case FilterType::Crop:
            return std::make_shared<Crop>();
        case FilterType::Curves:
            return std::make_shared<Curves>();
        case FilterType::Datascope:
            return std::make_shared<Datascope>();
        case FilterType::Dblur:
            return std::make_shared<Dblur>();
        case FilterType::Dctdnoiz:
            return std::make_shared<Dctdnoiz>();
        case FilterType::Deband:
            return std::make_shared<Deband>();
        case FilterType::Deblock:
            return std::make_shared<Deblock>();
        case FilterType::Decimate:
            return std::make_shared<Decimate>();
        case FilterType::Deconvolve:
            return std::make_shared<Deconvolve>();
        case FilterType::Dedot:
            return std::make_shared<Dedot>();
        case FilterType::Deflate:
            return std::make_shared<Deflate>();
        case FilterType::Deflicker:
            return std::make_shared<Deflicker>();
        case FilterType::Dejudder:
            return std::make_shared<Dejudder>();
        case FilterType::Derain:
            return std::make_shared<Derain>();
        case FilterType::Deshake:
            return std::make_shared<Deshake>();
        case FilterType::Despill:
            return std::make_shared<Despill>();
        case FilterType::Detelecine:
            return std::make_shared<Detelecine>();
        case FilterType::Dilation:
            return std::make_shared<Dilation>();
        case FilterType::Displace:
            return std::make_shared<Displace>();
        case FilterType::Dnn_classify:
            return std::make_shared<Dnn_classify>();
        case FilterType::Dnn_detect:
            return std::make_shared<Dnn_detect>();
        case FilterType::Dnn_processing:
            return std::make_shared<Dnn_processing>();
        case FilterType::Doubleweave:
            return std::make_shared<Doubleweave>();
        case FilterType::Drawbox:
            return std::make_shared<Drawbox>();
        case FilterType::Drawgraph:
            return std::make_shared<Drawgraph>();
        case FilterType::Drawgrid:
            return std::make_shared<Drawgrid>();
        case FilterType::Edgedetect:
            return std::make_shared<Edgedetect>();
        case FilterType::Elbg:
            return std::make_shared<Elbg>();
        case FilterType::Entropy:
            return std::make_shared<Entropy>();
        case FilterType::Epx:
            return std::make_shared<Epx>();
        case FilterType::Erosion:
            return std::make_shared<Erosion>();
        case FilterType::Estdif:
            return std::make_shared<Estdif>();
        case FilterType::Exposure:
            return std::make_shared<Exposure>();
        case FilterType::Extractplanes:
            return std::make_shared<Extractplanes>();
        case FilterType::Fade:
            return std::make_shared<Fade>();
        case FilterType::Feedback:
            return std::make_shared<Feedback>();
        case FilterType::Fftdnoiz:
            return std::make_shared<Fftdnoiz>();
        case FilterType::Fftfilt:
            return std::make_shared<Fftfilt>();
        case FilterType::Field:
            return std::make_shared<Field>();
        case FilterType::Fieldhint:
            return std::make_shared<Fieldhint>();
        case FilterType::Fieldmatch:
            return std::make_shared<Fieldmatch>();
        case FilterType::Fieldorder:
            return std::make_shared<Fieldorder>();
        case FilterType::Fillborders:
            return std::make_shared<Fillborders>();
        case FilterType::Floodfill:
            return std::make_shared<Floodfill>();
        case FilterType::Format:
            return std::make_shared<Format>();
        case FilterType::Fps:
            return std::make_shared<Fps>();
        case FilterType::Framepack:
            return std::make_shared<Framepack>();
        case FilterType::Framerate:
            return std::make_shared<Framerate>();
        case FilterType::Framestep:
            return std::make_shared<Framestep>();
        case FilterType::Freezedetect:
            return std::make_shared<Freezedetect>();
        case FilterType::Freezeframes:
            return std::make_shared<Freezeframes>();
        case FilterType::Fsync:
            return std::make_shared<Fsync>();
        case FilterType::Gblur:
            return std::make_shared<Gblur>();
        case FilterType::Geq:
            return std::make_shared<Geq>();
        case FilterType::Gradfun:
            return std::make_shared<Gradfun>();
        case FilterType::Graphmonitor:
            return std::make_shared<Graphmonitor>();
        case FilterType::Grayworld:
            return std::make_shared<Grayworld>();
        case FilterType::Greyedge:
            return std::make_shared<Greyedge>();
        case FilterType::Guided:
            return std::make_shared<Guided>();
        case FilterType::Haldclut:
            return std::make_shared<Haldclut>();
        case FilterType::Hflip:
            return std::make_shared<Hflip>();
        case FilterType::Histogram:
            return std::make_shared<Histogram>();
        case FilterType::Hqx:
            return std::make_shared<Hqx>();
        case FilterType::Hstack:
            return std::make_shared<Hstack>();
        case FilterType::Hsvhold:
            return std::make_shared<Hsvhold>();
        case FilterType::Hsvkey:
            return std::make_shared<Hsvkey>();
        case FilterType::Hue:
            return std::make_shared<Hue>();
        case FilterType::Huesaturation:
            return std::make_shared<Huesaturation>();
        case FilterType::Hwdownload:
            return std::make_shared<Hwdownload>();
        case FilterType::Hwmap:
            return std::make_shared<Hwmap>();
        case FilterType::Hwupload:
            return std::make_shared<Hwupload>();
        case FilterType::Hwupload_cuda:
            return std::make_shared<Hwupload_cuda>();
        case FilterType::Hysteresis:
            return std::make_shared<Hysteresis>();
        case FilterType::Identity:
            return std::make_shared<Identity>();
        case FilterType::Idet:
            return std::make_shared<Idet>();
        case FilterType::Il:
            return std::make_shared<Il>();
        case FilterType::Inflate:
            return std::make_shared<Inflate>();
        case FilterType::Interleave:
            return std::make_shared<Interleave>();
        case FilterType::Kirsch:
            return std::make_shared<Kirsch>();
        case FilterType::Lagfun:
            return std::make_shared<Lagfun>();
        case FilterType::Latency:
            return std::make_shared<Latency>();
        case FilterType::Lenscorrection:
            return std::make_shared<Lenscorrection>();
        case FilterType::Limitdiff:
            return std::make_shared<Limitdiff>();
        case FilterType::Limiter:
            return std::make_shared<Limiter>();
        case FilterType::Loop:
            return std::make_shared<Loop>();
        case FilterType::Lumakey:
            return std::make_shared<Lumakey>();
        case FilterType::Lut:
            return std::make_shared<Lut>();
        case FilterType::Lut1d:
            return std::make_shared<Lut1d>();
        case FilterType::Lut2:
            return std::make_shared<Lut2>();
        case FilterType::Lut3d:
            return std::make_shared<Lut3d>();
        case FilterType::Lutrgb:
            return std::make_shared<Lutrgb>();
        case FilterType::Lutyuv:
            return std::make_shared<Lutyuv>();
        case FilterType::Maskedclamp:
            return std::make_shared<Maskedclamp>();
        case FilterType::Maskedmax:
            return std::make_shared<Maskedmax>();
        case FilterType::Maskedmerge:
            return std::make_shared<Maskedmerge>();
        case FilterType::Maskedmin:
            return std::make_shared<Maskedmin>();
        case FilterType::Maskedthreshold:
            return std::make_shared<Maskedthreshold>();
        case FilterType::Maskfun:
            return std::make_shared<Maskfun>();
        case FilterType::Median:
            return std::make_shared<Median>();
        case FilterType::Mergeplanes:
            return std::make_shared<Mergeplanes>();
        case FilterType::Mestimate:
            return std::make_shared<Mestimate>();
        case FilterType::Metadata:
            return std::make_shared<Metadata>();
        case FilterType::Midequalizer:
            return std::make_shared<Midequalizer>();
        case FilterType::Minterpolate:
            return std::make_shared<Minterpolate>();
        case FilterType::Mix:
            return std::make_shared<Mix>();
        case FilterType::Monochrome:
            return std::make_shared<Monochrome>();
        case FilterType::Morpho:
            return std::make_shared<Morpho>();
        case FilterType::Msad:
            return std::make_shared<Msad>();
        case FilterType::Multiply:
            return std::make_shared<Multiply>();
        case FilterType::Negate:
            return std::make_shared<Negate>();
        case FilterType::Nlmeans:
            return std::make_shared<Nlmeans>();
        case FilterType::Noformat:
            return std::make_shared<Noformat>();
        case FilterType::Noise:
            return std::make_shared<Noise>();
        case FilterType::Normalize:
            return std::make_shared<Normalize>();
        case FilterType::Null:
            return std::make_shared<Null>();
        case FilterType::Oscilloscope:
            return std::make_shared<Oscilloscope>();
        case FilterType::Overlay:
            return std::make_shared<Overlay>();
        case FilterType::Pad:
            return std::make_shared<Pad>();
        case FilterType::Palettegen:
            return std::make_shared<Palettegen>();
        case FilterType::Paletteuse:
            return std::make_shared<Paletteuse>();
        case FilterType::Photosensitivity:
            return std::make_shared<Photosensitivity>();
        case FilterType::Pixdesctest:
            return std::make_shared<Pixdesctest>();
        case FilterType::Pixelize:
            return std::make_shared<Pixelize>();
        case FilterType::Pixscope:
            return std::make_shared<Pixscope>();
        case FilterType::Premultiply:
            return std::make_shared<Premultiply>();
        case FilterType::Prewitt:
            return std::make_shared<Prewitt>();
        case FilterType::Pseudocolor:
            return std::make_shared<Pseudocolor>();
        case FilterType::Psnr:
            return std::make_shared<Psnr>();
        case FilterType::Qp:
            return std::make_shared<Qp>();
        case FilterType::Random:
            return std::make_shared<Random>();
        case FilterType::Readeia608:
            return std::make_shared<Readeia608>();
        case FilterType::Readvitc:
            return std::make_shared<Readvitc>();
        case FilterType::Remap:
            return std::make_shared<Remap>();
        case FilterType::Removegrain:
            return std::make_shared<Removegrain>();
        case FilterType::Removelogo:
            return std::make_shared<Removelogo>();
        case FilterType::Reverse:
            return std::make_shared<Reverse>();
        case FilterType::Rgbashift:
            return std::make_shared<Rgbashift>();
        case FilterType::Roberts:
            return std::make_shared<Roberts>();
        case FilterType::Rotate:
            return std::make_shared<Rotate>();
        case FilterType::Scale:
            return std::make_shared<Scale>();
        case FilterType::Scale2ref:
            return std::make_shared<Scale2ref>();
        case FilterType::Scdet:
            return std::make_shared<Scdet>();
        case FilterType::Scharr:
            return std::make_shared<Scharr>();
        case FilterType::Scroll:
            return std::make_shared<Scroll>();
        case FilterType::Segment:
            return std::make_shared<Segment>();
        case FilterType::Select:
            return std::make_shared<Select>();
        case FilterType::Selectivecolor:
            return std::make_shared<Selectivecolor>();
        case FilterType::Separatefields:
            return std::make_shared<Separatefields>();
        case FilterType::Setdar:
            return std::make_shared<Setdar>();
        case FilterType::Setfield:
            return std::make_shared<Setfield>();
        case FilterType::Setparams:
            return std::make_shared<Setparams>();
        case FilterType::Setpts:
            return std::make_shared<Setpts>();
        case FilterType::Setrange:
            return std::make_shared<Setrange>();
        case FilterType::Setsar:
            return std::make_shared<Setsar>();
        case FilterType::Settb:
            return std::make_shared<Settb>();
        case FilterType::Shear:
            return std::make_shared<Shear>();
        case FilterType::Showinfo:
            return std::make_shared<Showinfo>();
        case FilterType::Showpalette:
            return std::make_shared<Showpalette>();
        case FilterType::Shuffleframes:
            return std::make_shared<Shuffleframes>();
        case FilterType::Shufflepixels:
            return std::make_shared<Shufflepixels>();
        case FilterType::Shuffleplanes:
            return std::make_shared<Shuffleplanes>();
        case FilterType::Sidedata:
            return std::make_shared<Sidedata>();
        case FilterType::Signalstats:
            return std::make_shared<Signalstats>();
        case FilterType::Siti:
            return std::make_shared<Siti>();
        case FilterType::Sobel:
            return std::make_shared<Sobel>();
        case FilterType::Sr:
            return std::make_shared<Sr>();
        case FilterType::Ssim:
            return std::make_shared<Ssim>();
        case FilterType::Ssim360:
            return std::make_shared<Ssim360>();
        case FilterType::Swaprect:
            return std::make_shared<Swaprect>();
        case FilterType::Swapuv:
            return std::make_shared<Swapuv>();
        case FilterType::Tblend:
            return std::make_shared<Tblend>();
        case FilterType::Telecine:
            return std::make_shared<Telecine>();
        case FilterType::Thistogram:
            return std::make_shared<Thistogram>();
        case FilterType::Threshold:
            return std::make_shared<Threshold>();
        case FilterType::Thumbnail:
            return std::make_shared<Thumbnail>();
        case FilterType::Tile:
            return std::make_shared<Tile>();
        case FilterType::Tiltandshift:
            return std::make_shared<Tiltandshift>();
        case FilterType::Tlut2:
            return std::make_shared<Tlut2>();
        case FilterType::Tmedian:
            return std::make_shared<Tmedian>();
        case FilterType::Tmidequalizer:
            return std::make_shared<Tmidequalizer>();
        case FilterType::Tmix:
            return std::make_shared<Tmix>();
        case FilterType::Tonemap:
            return std::make_shared<Tonemap>();
        case FilterType::Tpad:
            return std::make_shared<Tpad>();
        case FilterType::Transpose:
            return std::make_shared<Transpose>();
        case FilterType::Trim:
            return std::make_shared<Trim>();
        case FilterType::Unpremultiply:
            return std::make_shared<Unpremultiply>();
        case FilterType::Unsharp:
            return std::make_shared<Unsharp>();
        case FilterType::Untile:
            return std::make_shared<Untile>();
        case FilterType::V360:
            return std::make_shared<V360>();
        case FilterType::Varblur:
            return std::make_shared<Varblur>();
        case FilterType::Vectorscope:
            return std::make_shared<Vectorscope>();
        case FilterType::Vflip:
            return std::make_shared<Vflip>();
        case FilterType::Vfrdet:
            return std::make_shared<Vfrdet>();
        case FilterType::Vibrance:
            return std::make_shared<Vibrance>();
        case FilterType::Vif:
            return std::make_shared<Vif>();
        case FilterType::Vignette:
            return std::make_shared<Vignette>();
        case FilterType::Vmafmotion:
            return std::make_shared<Vmafmotion>();
        case FilterType::Vstack:
            return std::make_shared<Vstack>();
        case FilterType::W3fdif:
            return std::make_shared<W3fdif>();
        case FilterType::Waveform:
            return std::make_shared<Waveform>();
        case FilterType::Weave:
            return std::make_shared<Weave>();
        case FilterType::Xbr:
            return std::make_shared<Xbr>();
        case FilterType::Xcorrelate:
            return std::make_shared<Xcorrelate>();
        case FilterType::Xfade:
            return std::make_shared<Xfade>();
        case FilterType::Xmedian:
            return std::make_shared<Xmedian>();
        case FilterType::Xstack:
            return std::make_shared<Xstack>();
        case FilterType::Yadif:
            return std::make_shared<Yadif>();
        case FilterType::Yaepblur:
            return std::make_shared<Yaepblur>();
        case FilterType::Zoompan:
            return std::make_shared<Zoompan>();
        case FilterType::Allrgb:
            return std::make_shared<Allrgb>();
        case FilterType::Allyuv:
            return std::make_shared<Allyuv>();
        case FilterType::Cellauto:
            return std::make_shared<Cellauto>();
        case FilterType::Color:
            return std::make_shared<Color>();
        case FilterType::Colorchart:
            return std::make_shared<Colorchart>();
        case FilterType::Colorspectrum:
            return std::make_shared<Colorspectrum>();
        case FilterType::Ddagrab:
            return std::make_shared<Ddagrab>();
        case FilterType::Gradients:
            return std::make_shared<Gradients>();
        case FilterType::Haldclutsrc:
            return std::make_shared<Haldclutsrc>();
        case FilterType::Life:
            return std::make_shared<Life>();
        case FilterType::Mandelbrot:
            return std::make_shared<Mandelbrot>();
        case FilterType::Nullsrc:
            return std::make_shared<Nullsrc>();
        case FilterType::Pal75bars:
            return std::make_shared<Pal75bars>();
        case FilterType::Pal100bars:
            return std::make_shared<Pal100bars>();
        case FilterType::Rgbtestsrc:
            return std::make_shared<Rgbtestsrc>();
        case FilterType::Sierpinski:
            return std::make_shared<Sierpinski>();
        case FilterType::Smptebars:
            return std::make_shared<Smptebars>();
        case FilterType::Smptehdbars:
            return std::make_shared<Smptehdbars>();
        case FilterType::Testsrc:
            return std::make_shared<Testsrc>();
        case FilterType::Testsrc2:
            return std::make_shared<Testsrc2>();
        case FilterType::Yuvtestsrc:
            return std::make_shared<Yuvtestsrc>();
        case FilterType::Zoneplate:
            return std::make_shared<Zoneplate>();
        case FilterType::Nullsink:
            return std::make_shared<Nullsink>();
        case FilterType::A3dscope:
            return std::make_shared<A3dscope>();
        case FilterType::Abitscope:
            return std::make_shared<Abitscope>();
        case FilterType::Adrawgraph:
            return std::make_shared<Adrawgraph>();
        case FilterType::Agraphmonitor:
            return std::make_shared<Agraphmonitor>();
        case FilterType::Ahistogram:
            return std::make_shared<Ahistogram>();
        case FilterType::Aphasemeter:
            return std::make_shared<Aphasemeter>();
        case FilterType::Avectorscope:
            return std::make_shared<Avectorscope>();
        case FilterType::Showcqt:
            return std::make_shared<Showcqt>();
        case FilterType::Showcwt:
            return std::make_shared<Showcwt>();
        case FilterType::Showfreqs:
            return std::make_shared<Showfreqs>();
        case FilterType::Showspatial:
            return std::make_shared<Showspatial>();
        case FilterType::Showspectrum:
            return std::make_shared<Showspectrum>();
        case FilterType::Showspectrumpic:
            return std::make_shared<Showspectrumpic>();
        case FilterType::Showvolume:
            return std::make_shared<Showvolume>();
        case FilterType::Showwaves:
            return std::make_shared<Showwaves>();
        case FilterType::Showwavespic:
            return std::make_shared<Showwavespic>();
        case FilterType::Buffer:
            return std::make_shared<Buffer>();
        case FilterType::Buffersink:
            return std::make_shared<Buffersink>();
        default:
            return nullptr;
    }
}
